from ConfigParser import ConfigParser
from Translator import Translator
from Optimizer import Optimizer
class Grail:
    '''
    Class that contains functions to generate grail blocks
    '''
    filename=""
    blocks=[]
    def __init__(self,filename):
        '''
        constructor        
        @param filename: file containing config 
        @type filename: string
        '''
        self.filename=filename
    def getBlocks(self): 
        ''' 
        returns the blocks/sql statements generated by grail
        '''
        return self.blocks 
     
    def run(self):
        '''
        invokes the config parser, generates the sql statements and runs optimizer 
        '''
        Parser=ConfigParser(self.filename)
        config=Parser.configContent
        translator=Translator(config)
        translator.translate()
        self.blocks=translator.getBlocks()

        op=Optimizer(translator.getConvertedOptions(),self.blocks,translator.getSenders())
        op.run()
