#!/bin/sh

#echo "Running all tests"
#exit 0

if [ $# -ne 1 ]
then
	echo "error:expected only 1 argument"
	exit 1
fi

algo=$1
#algo_lst=('sssp' 'wcc' 'pagerank')
#check if input argument was valid
#if [[ !(" ${algo_lst[*]} " == *$algo*)  ]]; then
#	echo "error:input algo name is incorrect"
#	exit 1
#fi

#loads vertices and edges for the algorithm into the table using psql command
vertex_load_sql="./datagen/"$algo"/create_and_load_vertex.sql"
psql travis_ci_test -c "\i "$vertex_load_sql

edge_load_sql="./datagen/"$algo"/create_and_load_edge.sql"
psql travis_ci_test -c "\i "$edge_load_sql

#executes generated algorithmic sql and loads into next table of the db
algo_sql="./analytics/"$algo".sql"
psql travis_ci_test -c "\i "$algo_sql

#exports tuples from next table as flat file
psql travis_ci_test -t -c "select * from next order by id" > ./output/$algo.out
psql travis_ci_test -t -c "select * from next order by id"

#view the files
echo "golden output"
cat "./output/"$algo"_golden.out"
echo "algo output"
cat "./output/"$algo".out"


#compares the diff between golden file and exported file
python ./compareoutput.py -f "./output/"$algo"_golden.out" -F "./output/"$algo".out"
ret=$?
if [ $ret -ne 0 ]; then
	echo "Discrepancy in Algorithmic Output generated by GRAIL"
	exit 1
fi
echo "Successful"
exit 0
